// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Play$StronglyTyped from "./play.bs.js";
import * as Examples$StronglyTyped from "./examples.bs.js";

var component = ReasonReact.reducerComponent("App");

function getRoute(url) {
  var match = url[/* path */0];
  if (match) {
    if (match[0] === "examples" && !match[1]) {
      return /* Examples */2;
    } else {
      return /* NotFound */0;
    }
  } else {
    return /* Play */1;
  }
}

function renderRoute(route) {
  switch (route) {
    case 0 : 
        return React.createElement("h1", undefined, "not found");
    case 1 : 
        return ReasonReact.element(undefined, undefined, Play$StronglyTyped.make(/* array */[]));
    case 2 : 
        return ReasonReact.element(undefined, undefined, Examples$StronglyTyped.make(/* array */[]));
    
  }
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var watcherId = ReasonReact.Router[/* watchUrl */1]((function (url) {
                      debugger;
                      return Curry._1(self[/* send */3], /* RouteUpdate */[getRoute(url)]);
                    }));
              return Curry._1(self[/* onUnmount */4], (function () {
                            return ReasonReact.Router[/* unwatchUrl */2](watcherId);
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return renderRoute(self[/* state */1][/* route */0]);
            }),
          /* initialState */(function () {
              return /* record */[/* route */getRoute(ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0))];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _) {
              return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  component ,
  getRoute ,
  renderRoute ,
  make ,
  
}
/* component Not a pure module */
