// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";

function startsWith(input, word) {
  return new RegExp("^" + input).test(word[/* text */0]);
}

function resolveAll(promises) {
  return List.fold_left((function (acc, promise) {
                return acc.then((function (results) {
                              return promise.then((function (result) {
                                            return Promise.resolve(List.append(results, /* :: */[
                                                            result,
                                                            /* [] */0
                                                          ]));
                                          }));
                            }));
              }), Promise.resolve(/* [] */0), promises);
}

export {
  startsWith ,
  resolveAll ,
  
}
/* No side effect */
