// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE


function startsWith(input, word) {
  return new RegExp("^" + input).test(word[/* text */0]);
}

export {
  startsWith ,
  
}
/* No side effect */
