// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE


function startsWithStr(input, str) {
  return new RegExp("^" + input).test(str);
}

function startsWith(input, word) {
  return new RegExp("^" + input).test(word[/* text */0]);
}

export {
  startsWithStr ,
  startsWith ,
  
}
/* No side effect */
