// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Crash$StronglyTyped from "./crash.bs.js";
import * as Example$StronglyTyped from "./example.bs.js";

var component = ReasonReact.statelessComponent("Examples");

var example1_001 = /* words : :: */[
  /* record */[
    /* text */"Ursa",
    /* velocity */0.0,
    /* x */300.0,
    /* y */150.0
  ],
  /* [] */0
];

var example1_003 = /* base : tuple */[
  0.0,
  600.0
];

var example1_004 = /* crashCollector */Crash$StronglyTyped.crashSite(/* () */0);

var example1 = /* record */[
  /* gameOver */false,
  example1_001,
  /* ticks */0,
  example1_003,
  example1_004,
  /* bonus */undefined
];

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(undefined, undefined, Example$StronglyTyped.make(example1, "Ur", /* array */[]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  component ,
  example1 ,
  make ,
  
}
/* component Not a pure module */
