// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as Game$StronglyTyped from "./game.bs.js";
import * as Crash$StronglyTyped from "./crash.bs.js";
import * as Canvas$StronglyTyped from "./canvas.bs.js";

var ui = Canvas$StronglyTyped.initUi(600.0, 600.0, 30);

var initialState = /* record */[
  /* gameOver */false,
  /* words : [] */0,
  /* ticks */0,
  /* base : tuple */[
    30.0,
    ui[/* width */1] - 30.0
  ],
  /* crashCollector */Crash$StronglyTyped.crashSite(/* () */0)
];

Canvas$StronglyTyped.paint(ui, initialState, Game$StronglyTyped.nextState);

var height = 600.0;

var width = 600.0;

var fontSize = 30;

var baseMargin = 30.0;

export {
  height ,
  width ,
  fontSize ,
  baseMargin ,
  ui ,
  initialState ,
  
}
/* ui Not a pure module */
